### PR TITLE
remove babel-polyfill, fix tests, npm bump and code updates

### PR DESCRIPTION
**Pull request by jernejpregelj**
- replace babel-polyfill for runtime transform (smaller builds, does not break frontend apps)
- fix failling tests
- bumped npm packages
- fix npm update breaking change
- updated code according to lint

### CODE REVIEW

**Comment by diminator** [comment]
Hi @justmoon @emschwartz @adrianhopebailie could you have a look? This would resolve some of our driver packaging issues

**Comment by justmoon** [comment]
@jernejpregelj Why closed? Do you not want to merge this anymore?

**Comment by jernejpregelj** [comment]
@justmoon I closed it because I broke the PR by preparing to create https://github.com/bigchaindb/js-crypto-conditions

**Comment by jernejpregelj** [comment]
opened PR https://github.com/interledgerjs/five-bells-condition/pull/76

**Comment by justmoon** [comment]
Thanks, merged!

**Pull request closed without merging**
