### PR TITLE
remove babel-polyfill, fix tests, npm bump and code updates

### PR DESCRIPTION
**Pull request by jernejpregelj**
- replace
- babel-polyfill for runtime transform (smaller builds, does not break frontend apps)
- fix failling tests
- bumped npm packages
- fix npm update breaking change
- updated code according to lint

### CODE REVIEW

**Comment by jernejpregelj** [comment]
@justmoon babel-polyfill is huge blocker for us since it breaks lots of frontend frameworks. We are considering publishing our own npm package just to get this resolved as fast as possible!

**Comment by justmoon** [comment]
@jernejpregelj Got it! Sorry for the slow responses - been busy traveling and haven't had much time to catch up on my OSS projects.

If you would like, I'd be happy to add you and someone from your team (for code review) as committers, so you don't have to wait on us.

**Comment by diminator** [comment]
Thanks @justmoon 

Would be great to have someone on our team as a committer.
I would nominate @jernejpregelj

**Comment by jernejpregelj** [comment]
Thanks @justmoon I would be happy to help!

**Comment by justmoon** [comment]
@jernejpregelj You should have an invite to the Interledger.js Github org. If there is a second JavaScript developer you'd like to nominate as a maintainer (for code review purposes), let me know.

**Pull request merged**
